services:
  - type: web
    name: plants-vs-zombies-online
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        value: mongodb+srv://grimteam:%3Ckolop908%3E@cluster0.iifadf8.mongodb.net/
      - key: DB_NAME
        value: pvz_online
